# Session 11

[![Open and Execute in Google Colaboratory](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/astrojuanlu/ie-mbd-python-data-analysis-i/blob/main/sessions/Session%2011.ipynb)

- String methods on pandas columns
- Combining several dataframes
    - Concat
    - Join
    - Merge

## String methods on pandas columns

In [2]:
# BLUESKY_DATA_URL = "../data/bluesky_more_5000_likes_filtered.json"
BLUESKY_DATA_URL = (
    "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/"
    "raw/main/data/bluesky_more_5000_likes_filtered.json"
)

In [3]:
import pandas as pd

In [4]:
df = pd.read_json(BLUESKY_DATA_URL)
df.head()

,post_id,user_id,instance,date,text,langs,like_count,reply_count,repost_count,reply_to,replied_author,thread_root,thread_root_author,repost_from,reposted_author,quotes,quoted_author,labels,sent_label,sent_score
0,193115731,2648,ilovecitr.us,1976-05-31 15:05:10.052,Wins for Oppenheimer and Godzilla Minus One me...,[eng],6300,50,2138,NaN,NaN,NaN,NaN,65676,20990,NaN,NaN,NaN,2.0,0.807
1,193116187,2648,ilovecitr.us,1976-05-31 14:34:41.234,Today’s bake for brother’s 40th. I believe I h...,[eng],8266,171,1151,NaN,NaN,NaN,NaN,87314,46762,NaN,NaN,NaN,2.0,0.967
2,193116350,2648,ilovecitr.us,1976-05-31 14:31:01.544,Petition to honor Michael Shannon every Jan. 6,[eng],5327,87,1564,NaN,NaN,NaN,NaN,67433,78046,NaN,NaN,NaN,1.0,0.773
3,193116579,2648,ilovecitr.us,1976-05-30 13:35:00.156,Is it possible to fly a flag at twice-staff?,[eng],5566,55,1470,NaN,NaN,NaN,NaN,68732,64505,NaN,NaN,NaN,1.0,0.910
4,193116658,2648,ilovecitr.us,1976-05-30 13:33:00.024,1923: The world's richest man is an antisemite...,[eng],6719,87,2165,NaN,NaN,NaN,NaN,252171,33509,NaN,NaN,NaN,0.0,0.625

In [6]:
df.dtypes[:5]

post_id              int64
user_id              int64
instance            object
date        datetime64[ns]
text                object
dtype: object

In [5]:
df["instance"].str.split(".")

0      [ilovecitr, us]
1      [ilovecitr, us]
2      [ilovecitr, us]
3      [ilovecitr, us]
4      [ilovecitr, us]
            ...
330     [bsky, social]
331     [bsky, social]
332     [bsky, social]
333     [bsky, social]
334     [bsky, social]
Name: instance, Length: 335, dtype: object

In [9]:
df["instance_split"] = df["instance"].str.split(".")

In [10]:
df["instance_split"]

0      [ilovecitr, us]
1      [ilovecitr, us]
2      [ilovecitr, us]
3      [ilovecitr, us]
4      [ilovecitr, us]
            ...
330     [bsky, social]
331     [bsky, social]
332     [bsky, social]
333     [bsky, social]
334     [bsky, social]
Name: instance_split, Length: 335, dtype: object

In [11]:
df["instance_split"].str.get(0)

0      ilovecitr
1      ilovecitr
2      ilovecitr
3      ilovecitr
4      ilovecitr
         ...
330         bsky
331         bsky
332         bsky
333         bsky
334         bsky
Name: instance_split, Length: 335, dtype: object

String methods also work for other objects!

In [ ]:
df["instance"].str.split(".").str.get(0)

## Exercises

### 1. Columns of dictionaries

Read the Rick & Morty data. The goal is to compute the average rating per season.

For that, notice that the rating column contains a dictionary with 1 key. Extract the numeric value and place it under a new column called "rating_num". Then, use groupby operations to compute the average rating per season.

In [12]:
import requests

RICK_MORTY_DATA_URL = (
    "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/"
    "raw/main/data/rick-and-morty.json"
)

rm_data = requests.get(RICK_MORTY_DATA_URL).json()
print(type(rm_data), len(rm_data))

<class 'dict'> 24

In [14]:
rm_df = pd.DataFrame.from_records(rm_data["_embedded"]["episodes"])
rm_df.head()

,id,url,name,season,number,type,airdate,airtime,airstamp,runtime,rating,image,summary,_links
0,14308,https://www.tvmaze.com/episodes/14308/rick-and...,Pilot,1,1,regular,2013-12-02,22:30,2013-12-03T03:30:00+00:00,30,{'average': 8.6},{'medium': 'https://static.tvmaze.com/uploads/...,<p>Rick takes Morty to another dimension to ge...,{'self': {'href': 'https://api.tvmaze.com/epis...
1,14309,https://www.tvmaze.com/episodes/14309/rick-and...,Lawnmower Dog,1,2,regular,2013-12-09,22:30,2013-12-10T03:30:00+00:00,30,{'average': 8.9},{'medium': 'https://static.tvmaze.com/uploads/...,"<p>Morty's small, white dog Snuffles gets on t...",{'self': {'href': 'https://api.tvmaze.com/epis...
2,14310,https://www.tvmaze.com/episodes/14310/rick-and...,Anatomy Park,1,3,regular,2013-12-16,22:30,2013-12-17T03:30:00+00:00,30,{'average': 9},{'medium': 'https://static.tvmaze.com/uploads/...,<p>It's around Christmas time and Jerry's pare...,{'self': {'href': 'https://api.tvmaze.com/epis...
3,14311,https://www.tvmaze.com/episodes/14311/rick-and...,M. Night Shaym-Aliens!,1,4,regular,2014-01-13,22:30,2014-01-14T03:30:00+00:00,30,{'average': 9},{'medium': 'https://static.tvmaze.com/uploads/...,<p>Rick and Morty try to get to the bottom of ...,{'self': {'href': 'https://api.tvmaze.com/epis...
4,14312,https://www.tvmaze.com/episodes/14312/rick-and...,Meeseeks and Destroy,1,5,regular,2014-01-20,22:30,2014-01-21T03:30:00+00:00,30,{'average': 9},{'medium': 'https://static.tvmaze.com/uploads/...,<p>Rick provides the family with a solution to...,{'self': {'href': 'https://api.tvmaze.com/epis...

In [21]:
rm_df["rating_num"] = rm_df["rating"].str.get("average")

In [25]:
average_rating = rm_df.groupby("season")["rating_num"].mean()
average_rating

season
1    9.009091
2    9.260000
3    9.010000
4    8.510000
5    8.580000
Name: rating_num, dtype: float64

## Combining several dataframes

### Concat

`pd.concat` adds one dataframe after another, either vertically (along rows, the default) or horizontally (along columns). It is useful when you have several dataframes that relate to the same data and you want to combine them into one, for example paginated results.

In [ ]:
df_madrid = pd.read_csv(
    "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/raw/main/data/grandes-tenedores-madrid.csv"
)
df_madrid.head()

In [ ]:
len(df_madrid)

Let's artificially split the dataframe using `.iloc[]`. It's like `.loc[]`, but works by index instead of by label.

The first 100 rows will go in one dataset, the remaining rows into another:

In [ ]:
df_madrid_1 = df_madrid.iloc[:100]
df_madrid_1.head(1)

In [ ]:
df_madrid_2 = df_madrid.iloc[100:]
df_madrid_2.head(1)

In [ ]:
len(df_madrid_1) + len(df_madrid_2) == len(df_madrid)

In [ ]:
df_madrid_concat = pd.concat([df_madrid_1, df_madrid_2])

In [ ]:
df_madrid_concat.equals(df_madrid)

Alternatively, we can split by columns:

In [ ]:
df_madrid_left = df_madrid.iloc[:, :11]
df_madrid_left.head(1)

In [ ]:
df_madrid_right = df_madrid.iloc[:, 11:]
df_madrid_right.head(1)

In [ ]:
df_madrid_concat_cols = pd.concat([df_madrid_left, df_madrid_right], axis="columns")

In [ ]:
df_madrid_concat_cols.equals(df_madrid)

## Exercises

### 2. More split and concat

Using the same Rick & Morty data, split the data if five datasets, one per season. Then, concat it all again. At the end, check that the assembled dataframe and the original one are the same.

### Merge

In [ ]:
df_spain = pd.read_csv(
    # "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/raw/main/data/megatenedores_estatal_2024.csv"
    "../data/megatenedores_estatal_2024.csv"
)
df_spain.head()

In [ ]:
df_madrid_company_data = df_madrid.loc[:, ["NIF", "Filial propietaria directa", "Matriz"]]
df_madrid_company_data.head()

In [ ]:
len(df_madrid_company_data)

In [ ]:
df_madrid_company_data["Matriz"].nunique()

## Exercises

### 3. European Commission lobbists

Below you can find some data coming from Civio on lobby meetings at the European Commission.

In [ ]:
df_euco = pd.read_csv(
    "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/raw/main/data/commission-lobbists-meetings.csv"
)
df_euco.head()

In [ ]:
df_euco.loc[df_euco["nr"] > 10]

However, we know very little about the "lobbyst". Below, you can find some extra information (AI-generated) on some of them.

In [ ]:
lobby_data = pd.read_csv(
    "https://github.com/astrojuanlu/ie-mbd-python-data-analysis-i/raw/main/data/"
    "lobby_data_ai.csv"
)
lobby_data.head()

Combine both datasets to answer these questions:

- What are the top 10 lobbysts in terms of number of meetings?
- How many meetings happened with US vs with EU-based lobbysts?
- What was the most common policy orientation of the meetings?
- Now, answer the same questions, but using only meetings with a "high" number of representatives (let's use `nr > mean(nr)`)

### Join

The `.join` method is like the `.merge` one, but it's more efficient when working with indexes.

In [ ]:
df_madrid_company_data.head(1)

In [ ]:
df_spain.head(1)

In [ ]:
df_spain.set_index("Matriz")

In [ ]:
df_spain.set_index("Matriz").join(df_madrid_company_data.set_index("Matriz"))